
project_id = "fbflwhiwejjowqwaqjtx"

# Auth configuration
[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.external.google]
enabled = true
# You will need to set these values in the Supabase dashboard
# client_id = ""
# secret = ""
