// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbflwhiwejjowqwaqjtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiZmx3aGl3ZWpqb3dxd2FxanR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0OTQ5NzEsImV4cCI6MjA1OTA3MDk3MX0.NwxyyC-9tSxT-pzSvNpmWKEY9GhY33oBqQpbrvjtkXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);